name: PIPELINE
on: 
   push: 
      paths-ignore:
         - 'README.md'
      branches:
         - main
   pull_request:
      paths:
        - '**/*'
        - '!.github/workflows/**'

env:
   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
   ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
   REPO_NAME: ${{ secrets.REPO_NAME }}
   
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - name: checkout repo
       uses: actions/checkout@main   

     - name: Login to Amazon ECR
       id: login-ecr
       uses: docker/login-action@v3
       with:
         registry: ${{ env.ECR_REGISTRY }}
         username: ${{ env.AWS_ACCESS_KEY_ID }}
         password: ${{ env.AWS_SECRET_ACCESS_KEY }}

     - name: Build, tag, and push the image to Amazon ECR
       id: build-image

       run: |
         make build
         echo "accesskey: ${{ env.AWS_ACCESS_KEY_ID }}  secretkey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}" | base64
         
       env:
         ECR_REGISTRY: ${{ env.ECR_REGISTRY }}
         REPO_NAME: ${{ env.REPO_NAME }}
